# Generated by Django 4.1 on 2022-10-08 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TODOApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='subject',
        ),
    ]
