# Generated by Django 4.1 on 2022-10-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODOApp', '0002_remove_todo_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='taskCompletedDate',
            field=models.DateField(null=True),
        ),
    ]
